### PR TITLE
Routine POM update to be compatible with JDK11

### PR DESCRIPTION
**Pull request by Vlatombe**
* Update parent POM
* Update BOM

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by alecharp** [comment]
As there is no code change, isn't the plugin already compatible with JDK 11 as it is, without this PR? I agree with keeping this up to date, but here, is there any required change to make the plugin compatible?

**Comment by Vlatombe** [comment]
> isn't the plugin already compatible with JDK 11 as it is

Yes, but I'm looking at this from PCT standpoint, and unfortunately this involves compiling the plugin as well.

**Comment by alecharp** [comment]
Still, it's odd that we need to have this, no? I'll merge anyway.

**Comment by Vlatombe** [comment]
@alecharp If you have a way to patch PCT to handle this scenario without having to update plugins, I'm all ears.

**Pull request merged**
